spring.application.name=alumni-platform

#===========================
# DATABASE
#===========================
spring.datasource.url=jdbc:postgresql://ep-sweet-sound-ag4hjsmb-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require

# ✅ Credentials separated
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sMr2Ggp6LKiV

spring.datasource.driver-class-name=org.postgresql.Driver
#===========================
# JPA / HIBERNATE 
#===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#===========================
# JWT SECRET 
#===========================
app.jwt.secret=f5341909696933bf565d443a0815a0472082819d03b6b222f84272742c3e7698
app.jwt.expiration=86400000
